#
#	MetaCall Library by Parra Studios
#	Travis CD/CI infrastructure for MetaCall.
#
#	Copyright (C) 2016 - 2019 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
#
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#
#		http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#

language: cpp

branches:
  only:
  - develop

sudo: required

services:
  - docker

dist: trusty

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.22.0
    - GHR_VERSION: 0.12.0
    - GIT_SUBMODULE_STRATEGY: recursive
    - IMAGE_REGISTRY: registry.gitlab.com
    - IMAGE_NAME: registry.gitlab.com/$TRAVIS_REPO_SLUG
    - ARTIFACTS_PATH: $TRAVIS_BUILD_DIR/artifacts

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -sL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - $TRAVIS_BUILD_DIR/docker-compose.sh pull
  - $TRAVIS_BUILD_DIR/docker-compose.sh build-cache
  - $TRAVIS_BUILD_DIR/docker-compose.sh pack

after_script:
  - curl -sL https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz | tar zx
  - chmod +x ghr_v${GHR_VERSION}_linux_amd64/ghr
  - sudo mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/local/bin
  - |
      ghr -t $GITHUB_TOKEN -u $GITHUB_USER -r $TRAVIS_REPO_SLUG -c $TRAVIS_COMMIT \
      -n "Test Automated Releases" -b "From Travis" -replace \
      v0.1.8 $ARTIFACTS_PATH/packages/

# - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $TRAVIS_BUILD_DIR ghr -t  -u user -r $TRAVIS_REPO_SLUG -replace $TRAVIS_TAG $ARTIFACTS_PATH/packages/
