#
# MetaCall Library by Parra Studios
# Copyright (C) 2016 - 2017 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
#

version: "3"

services:
  deps:
    image: metacall/core_deps
    container_name: metacall_core_deps
    build:
      context: .
      dockerfile: tools/base/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_TOOLS_PATH: $METACALL_PATH/tools
        METACALL_BASE_IMAGE: ubuntu:xenial
    environment:
      DEBIAN_FRONTEND: noninteractive
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip

  deps_node:
    image: metacall/core_deps_node
    container_name: metacall_core_deps_node
    build:
      context: .
      dockerfile: tools/node/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_BUILD_TYPE_NAME: Release
    environment:
      DEBIAN_FRONTEND: noninteractive

  core:
    image: metacall/core
    container_name: metacall_core
    build:
      context: .
      dockerfile: tools/core/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_BUILD_TYPE: release
        METACALL_BUILD_OPTIONS: root python ruby netcore v8 nodejs distributable tests scripts dynamic install
    environment:
      DEBIAN_FRONTEND: noninteractive
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip
      LOADER_LIBRARY_PATH: $METACALL_PATH/build
      LOADER_SCRIPT_PATH: $METACALL_PATH/build/scripts
      CONFIGURATION_PATH: $METACALL_PATH/build/configurations/global.json
      SERIAL_LIBRARY_PATH: $METACALL_PATH/build
    depends_on:
      - deps
