#
# MetaCall Library by Parra Studios
# Copyright (C) 2016 - 2017 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
#

version: "3.7"

# TODO: Implement multiple image building allowing V8 at the same too
# V8 and NodeJS cannot run in the same instance because two V8 of different
# versions launched in the same process does not work well

services:
  deps:
    image: metacall/core_deps
    container_name: metacall_core_deps
    build:
      context: .
      dockerfile: tools/base/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_TOOLS_PATH: $METACALL_PATH/tools
        METACALL_BASE_IMAGE: $METACALL_BASE_IMAGE
        METACALL_INSTALL_OPTIONS: root base python ruby netcore nodejs rapidjson funchook # v8rep51
    environment:
      DEBIAN_FRONTEND: noninteractive
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip

  deps_node:
    image: metacall/core_deps_node
    container_name: metacall_core_deps_node
    build:
      context: .
      dockerfile: tools/node/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_NODE_BUILD_TYPE: $METACALL_NODE_BUILD_TYPE
        METACALL_BASE_IMAGE: $METACALL_BASE_IMAGE
    environment:
      DEBIAN_FRONTEND: noninteractive

  dev:
    image: metacall/core_dev
    container_name: metacall_core_dev
    build:
      context: .
      dockerfile: tools/dev/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_BUILD_TYPE: $METACALL_CORE_BUILD_TYPE
        METACALL_BUILD_OPTIONS: root python ruby netcore nodejs distributable tests scripts dynamic install # v8
    environment:
      DEBIAN_FRONTEND: noninteractive
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip
      LOADER_LIBRARY_PATH: $METACALL_PATH/build
      LOADER_SCRIPT_PATH: $METACALL_PATH/build/scripts
      CONFIGURATION_PATH: $METACALL_PATH/build/configurations/global.json
      SERIAL_LIBRARY_PATH: $METACALL_PATH/build
      DETOUR_LIBRARY_PATH: $METACALL_PATH/build
    depends_on:
      - deps

  core:
    image: metacall/core
    container_name: metacall_core
    build:
      context: .
      dockerfile: tools/core/Dockerfile
      args:
        METACALL_PATH: $METACALL_PATH
        METACALL_BASE_IMAGE: $METACALL_BASE_IMAGE
        METACALL_RUNTIME_OPTIONS: root base python ruby netcore nodejs # v8
    environment:
      DEBIAN_FRONTEND: noninteractive
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip
      LOADER_LIBRARY_PATH: /usr/local/lib
      LOADER_SCRIPT_PATH: /usr/local/scripts
      CONFIGURATION_PATH: /usr/local/share/metacall/configurations/global.json
      SERIAL_LIBRARY_PATH: /usr/local/lib
      DETOUR_LIBRARY_PATH: /usr/local/lib
    depends_on:
      - dev
